/**
 * Writes the per-example page of the elody-docs "SHACL UI" section from the
 * showcase output: for every example of the SHACL 1.2 UI spec, the shapes,
 * the generated Elody declaration, the generated GraphQL, the screenshot of
 * what the PWA renders, and what Elody left out.
 *
 * usage: tsx scripts/showcase-docs.ts <showcase-out> <elody-docs/docs/services/elody-frontend/shacl-ui>
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";

const out = process.argv[2];
const target = process.argv[3];
const manifest = JSON.parse(readFileSync(join(out, "manifest.json"), "utf-8"));
const SPEC = "https://w3c.github.io/data-shapes/shacl12-ui/";

const strip = (ttl: string) => ttl.split("\n").filter((line) => !line.startsWith("@prefix")).join("\n").trim();
const fence = (lang: string, body: string) => "````" + lang + "\n" + body.trim() + "\n````";
const title = (row: any) => row.title || row.section;

const verdict = (row: any) => {
  if (row.status !== "generated") return { text: "Not rendered", tone: "danger" };
  const left = (row.notes as string[]).filter((n) => /left out|has no |not override/.test(n));
  if (!row.hasForm || left.length) return { text: "Rendered in part", tone: "warning" };
  return { text: "Rendered", tone: "tip" };
};

const sections: string[] = [];
const rows: string[] = [];
for (const row of manifest) {
  const n = row.id.slice(0, 2);
  const v = verdict(row);
  const anchor = `example-${row.id.toLowerCase()}`;
  rows.push(`| [${n}](#${anchor}) | ${title(row)} | \`${row.section}\` | <Badge type="${v.tone}" text="${v.text}" /> |`);

  const dir = join(out, row.id);
  const parts: string[] = [`## ${n} · ${title(row)} {#${anchor}}`, "", `<Badge type="${v.tone}" text="${v.text}" /> Spec section [\`${row.section}\`](${SPEC}#${row.section})`, ""];
  if (row.status === "generated") parts.push(`![${title(row)} rendered by Elody](/images/shacl-ui/${row.id}.png)`, "");
  if (row.notes.length) {
    parts.push("**What Elody did with it**", "");
    for (const note of row.notes) parts.push(`- ${note}`);
    parts.push("");
  }
  parts.push(`::: details SHACL UI shapes (from the spec)\n${fence("turtle", strip(readFileSync(join(dir, "shapes.ttl"), "utf-8")))}\n:::`);
  if (existsSync(join(dir, "data.ttl")))
    parts.push(`::: details Data graph (from the spec)\n${fence("turtle", strip(readFileSync(join(dir, "data.ttl"), "utf-8")))}\n:::`);
  if (row.status === "generated") {
    parts.push(`::: details Elody declaration (generated by \`fromShacl\`)\n${fence("turtle", readFileSync(join(dir, "declaration.ui.ttl"), "utf-8"))}\n:::`);
    parts.push(`::: details GraphQL (generated by \`elody-ui generate\`)\n${fence("graphql", readFileSync(join(dir, "documents.graphql"), "utf-8"))}\n:::`);
    const fields = JSON.parse(readFileSync(join(dir, "inputFields.json"), "utf-8"));
    if (Object.keys(fields).length)
      parts.push(`::: details Generated custom input fields\n${fence("json", JSON.stringify(fields, null, 2))}\n:::`);
  }
  sections.push(parts.join("\n"));
}

const page = `---
outline: [2, 2]
---

# SHACL UI spec examples

Every example of the [SHACL 1.2 UI specification](${SPEC}) put through the
Elody pipeline described in [SHACL UI in Elody](./index.md): the spec's shapes
are converted to an Elody UI declaration, the declaration is generated into
GraphQL, the GraphQL is validated and executed by baseGraphql, and the result
is rendered by the PWA. The screenshots show the create form (left) and the
detail page (right), filled with the spec's own data where it gives any.

This page is generated by \`modules/uiDeclarationModule/scripts/showcase.sh\`
and \`scripts/showcase-docs.ts\`; regenerate it after the spec or the pipeline
changes.

| # | Example | Spec section | Result |
|---|---|---|---|
${rows.join("\n")}

${sections.join("\n\n")}
`;
mkdirSync(target, { recursive: true });
writeFileSync(join(target, "examples.md"), page);
console.log(`wrote ${manifest.length} examples to ${join(target, "examples.md")}`);
