/**
 * Step 3 of the showcase: turn the executed results into Storybook stories in a
 * PWA checkout (feat/storybook), so the real PWA components render what Elody's
 * GraphQL returned: DynamicForm with the create form's formFields (as
 * DynamicFormModal passes them) and EntityElementWindow with the detail window.
 *
 * usage: tsx scripts/showcase-stories.ts <showcase-out> <pwa checkout>
 */
import { mkdirSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";

const out = process.argv[2];
const pwa = process.argv[3];
const manifest = JSON.parse(readFileSync(join(out, "manifest.json"), "utf-8"));

const nest = (flat: Record<string, string>) => {
  const root: Record<string, any> = {};
  for (const [key, value] of Object.entries(flat)) {
    const parts = key.split(".");
    let node = root;
    for (const part of parts.slice(0, -1)) node = node[part] ??= {};
    node[parts[parts.length - 1]] = value;
  }
  return root;
};

const examples: Record<string, unknown> = {};
const exportsList: string[] = [];
for (const row of manifest) {
  if (row.status !== "generated") continue;
  const executed = JSON.parse(readFileSync(join(out, row.id, "executed.json"), "utf-8"));
  const translations = JSON.parse(readFileSync(join(out, row.id, "translations.json"), "utf-8"));
  const entity = executed.detail?.data?.SpecExampleEntity;
  examples[row.id] = {
    id: row.id,
    title: row.title || row.section,
    section: row.section,
    formQuery: row.formQuery ?? null,
    formLabel: executed.form?.data?.GetDynamicForm?.label ?? null,
    formFields: executed.form?.data?.GetDynamicForm?.name?.formFields ?? null,
    window: entity?.entityView?.column?.elements?.windowElement ?? null,
    intialValues: entity?.intialValues ?? {},
    // the generated label texts, plus the platform label of the create button (base translations)
    messages: { ...nest(translations.en ?? {}), actions: { labels: { create: "Create" } } },
    relationFields: Object.values(executed.form?.data?.GetDynamicForm?.name?.formFields ?? {}).some((f: any) => /Relations$/.test(f?.inputField?.type ?? "")),
  };
  const name = `Example${row.id.replace(/-(\w)/g, (_: string, c: string) => c.toUpperCase()).replace(/^(\d+)/, "$1_")}`;
  exportsList.push(`export const ${name}: Story = { name: ${JSON.stringify(`${row.id.slice(0, 2)} · ${row.title || row.section}`)}, args: { example: examples[${JSON.stringify(row.id)}] } };`);
}

const dir = join(pwa, "src", "showcase");
mkdirSync(dir, { recursive: true });
writeFileSync(join(dir, "shaclUiShowcase.data.ts"), `// GENERATED by uiDeclarationModule/scripts/showcase-stories.ts\nexport const examples: Record<string, any> = ${JSON.stringify(examples, null, 2)};\n`);
writeFileSync(
  join(dir, "ShaclUiShowcase.stories.ts"),
  `// GENERATED by uiDeclarationModule/scripts/showcase-stories.ts
// SHACL 1.2 UI spec examples → Elody declaration → GraphQL → executed by baseGraphql → rendered here.
import type { Meta, StoryObj } from "@storybook/vue3-vite";
import { defineComponent, provide, type PropType } from "vue";
import { useRouter } from "vue-router";
import DynamicForm from "@/components/dynamicForms/DynamicForm.vue";
import EntityElementWindow from "@/components/entityElements/EntityElementWindow.vue";
import { useFormHelper } from "@/composables/useFormHelper";
import { i18n } from "@/main";
import { examples } from "./shaclUiShowcase.data";

const Showcase = defineComponent({
  name: "ShaclUiShowcase",
  components: { DynamicForm, EntityElementWindow },
  props: { example: { type: Object as PropType<any>, required: true } },
  setup(props) {
    // language-tagged text renders as a multilingual field: a client turns this feature on
    provide("config", { customization: {}, features: { supportsMultilingualMetadataEditing: true } });
    const formId = \`showcase-\${props.example.id}\`;
    const { getForm, createForm } = useFormHelper();
    if (!getForm(formId)) createForm(formId, { intialValues: props.example.intialValues, relationValues: {} } as any);
    i18n.global.mergeLocaleMessage("en", props.example.messages);
    return { formId, router: useRouter() };
  },
  template: \`
    <div class="grid grid-cols-2 gap-6 p-6 items-start" style="width: 1200px">
      <section class="bg-white rounded-lg border border-neutral-light p-4">
        <h3 class="text-sm uppercase tracking-wide text-text-light mb-3">Create form · {{ example.formLabel ?? "none" }}</h3>
        <DynamicForm
          v-if="example.formFields"
          :dynamic-form-query="example.formQuery"
          :modal-form-fields="example.formFields"
          :router="router"
          tab-name=""
        />
        <p v-else class="text-sm text-text-light">No field of this shape can be entered in an Elody create form.</p>
        <p v-if="example.relationFields" class="text-xs text-text-light mt-3">Relation dropdowns load their options from the collection; Storybook has none behind it.</p>
      </section>
      <section>
        <h3 class="text-sm uppercase tracking-wide text-text-light mb-3">Detail page</h3>
        <EntityElementWindow v-if="example.window" :element="example.window" :identifiers="[formId]" :form-id="formId" />
      </section>
    </div>\`,
});

const meta: Meta<typeof Showcase> = {
  title: "SHACL UI/Spec examples",
  component: Showcase,
  parameters: { layout: "fullscreen" },
};
export default meta;
type Story = StoryObj<typeof Showcase>;

${exportsList.join("\n")}
`,
);
console.log(`wrote ${exportsList.length} stories to ${dir}`);
